Added client_id for non embedded signature requests
hellosign/hellosign-python-sdk pull request #57
Opened 2019-11-29 11:29 UTC by neillom

Added client_id for non embedded requests to enable white-labeling.

Fix for reported issue #40

2019-12-03 23:44 UTC, martinytodorov requested changes
Hey Marc, I added one suggestion and because I previously merged a big PR yours is now in conflict.

Can you try to fix it, or may be just pull the new changes that were merged and add your changes again (might be faster).

Thanks for adding that!

2019-12-03 23:44 UTC, martinytodorov commented on hellosign_sdk/hsclient.py
> +    def _send_signature_request(self, test_mode=False, client_id=None, files=None, file_urls=None, title=None, subject=None, message=None, signing_redirect_url=None, signers=None, cc_email_addresses=
```suggestion
    def _send_signature_request(self, test_mode=False, client_id=None, files=None, file_urls=None, title=None, subject=None, message=None, signing_redirect_url=None, signers=None, cc_email_addresses=None, form_fields_per_document=None, use_text_tags=False, hide_text_tags=False, metadata=None, ux_version=None, allow_decline=False, is_for_embedded_signing=False):
```

2019-12-04 18:13 UTC, neillom commented
Hey Martin, included fix for issue I spotted after yesterday's merge.

2019-12-07 01:04 UTC, martinytodorov approved these changes
Looks good. This `.replace('null','{}')` will fix the signing_options for now, but I am about to open another PR that will move this into one of those format functions in HSFormat.

2019-12-07 01:04 UTC, merged