Minor fixes to get testing successfully working again.
hellosign/hellosign-python-sdk pull request #74
Opened 2020-05-11 13:43 UTC by neillom

Some minor syntax updates to fix unit tests. All testing now successfully passes.

2020-05-15 16:00 UTC, gpopoteur commented on hellosign_sdk/tests/unit_tests/test_hsformat.py
> +        attribute = hasattr(result[list(keys)[0]], 'read') #check if file (can be read)
Good catch, `.keys()` returns a `dict_keys` object in Python 3. 

Wondering if we want to call `list()` in line 43 (eg: `key = list(result.keys())`) that way the `key` variable is a list and maintains the same behavior as in Python 2.7

2020-05-15 16:03 UTC, gpopoteur requested changes
Requesting a small change, that way the `keys` variable stays a list

2020-05-15 16:03 UTC, gpopoteur commented on hellosign_sdk/tests/unit_tests/test_hsformat.py
> +        attribute = hasattr(result[list(keys)[0]], 'read') #check if file (can be read)
Yeah, on second thought I think it will be easier to read if we do it in line `43` when we declare the `keys` variable.

2022-04-21 14:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hellosign/hellosign-python-sdk?pullRequest=74) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hellosign/hellosign-python-sdk?pullRequest=74) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hellosign/hellosign-python-sdk?pullRequest=74) it.</sub>

2023-10-17 15:31 UTC, jtreminio-dropbox commented
Please use the new OpenAPI SDK: https://pypi.org/project/dropbox-sign/

2023-10-17 15:31 UTC, closed without merging